apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allowed-image-registries
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: validate-image-registry
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Only images from docker.io are allowed."
        pattern:
          spec:
            containers:
              - image: "docker.io/* | quay.io/* | ghcr.io/* | ecr-public.aws.com/*"
 
