name: Trivy Security

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  trivy-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy Security Gate
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: backend
          scanners: vuln
          severity: HIGH,CRITICAL
          exit-code: '1'
